from PySide6.QtWidgets import QVBoxLayout
from PySide6.QtCore import Qt

from qfluentwidgets import SubtitleLabel, BodyLabel, LineEdit, PasswordLineEdit, EditableComboBox, PlainTextEdit, PushButton

from gui.component.dialog import DialogBase
from gui.component.widget import ScrollArea

from util.common.config import config, DefaultValue

import logging

logger = logging.getLogger(__name__)

class SummarySettingsDialog(DialogBase):
    def __init__(self, parent = None):
        super().__init__(parent)

        self.init_UI()

    def init_UI(self):
        self.caption_lab = SubtitleLabel(self.tr("Configure AI Summary Service"), self)

        base_url_lab = BodyLabel(self.tr("API Endpoint (Base URL)"))
        self.base_url_box = LineEdit(self)
        self.base_url_box.setPlaceholderText(self.tr("OpenAI-compatible endpoint, e.g. https://api.deepseek.com"))
        self.base_url_box.setText(config.get(config.summary_base_url))
        self.base_url_box.setClearButtonEnabled(True)

        api_key_lab = BodyLabel(self.tr("API Key"))
        self.api_key_box = PasswordLineEdit(self)
        self.api_key_box.setPlaceholderText(self.tr("API Key, e.g. sk-xxxxxxxxxxxxxxxx"))
        self.api_key_box.setText(config.get(config.summary_api_key))

        model_lab = BodyLabel(self.tr("Model Name"))
        self.model_box = EditableComboBox(self)
        self.model_box.addItems([
            "deepseek-v4-flash",
            "deepseek-chat",
            "qwen-plus",
            "gpt-4o-mini"
        ])
        self.model_box.setCurrentText(config.get(config.summary_model))
        self.model_box.setFixedWidth(360)

        prompt_lab = BodyLabel(self.tr("Summary Prompt"))
        self.prompt_box = PlainTextEdit(self)
        self.prompt_box.setPlaceholderText(self.tr("Use {text} as the placeholder for the transcript content"))
        self.prompt_box.setPlainText(config.get(config.summary_prompt))
        self.prompt_box.setMinimumHeight(160)

        self.restore_default_btn = PushButton(self.tr("Restore Default"), self)
        self.restore_default_btn.clicked.connect(self.on_restore_default)

        tip_lab = BodyLabel(self.tr("The endpoint must implement the OpenAI chat/completions protocol. The transcript is generated by speech-to-text (ASR); long transcripts require a model with a sufficient context window."))
        tip_lab.setWordWrap(True)

        layout = QVBoxLayout()
        layout.setContentsMargins(0, 0, 0, 0)
        layout.addWidget(self.caption_lab)
        layout.setSpacing(10)
        layout.addWidget(base_url_lab)
        layout.addWidget(self.base_url_box)
        layout.addWidget(api_key_lab)
        layout.addWidget(self.api_key_box)
        layout.addWidget(model_lab)
        layout.addWidget(self.model_box, 0, Qt.AlignmentFlag.AlignLeft)
        layout.addWidget(prompt_lab)
        layout.addWidget(self.prompt_box)
        layout.addWidget(self.restore_default_btn, 0, Qt.AlignmentFlag.AlignRight)
        layout.addSpacing(5)
        layout.addWidget(tip_lab)

        # 表单放入滚动容器：窗口高度不足时表单内部滚动，避免布局被压缩后控件相互重叠
        self.scroll_area = ScrollArea(self)
        self.scroll_area.setScrollLayout(layout)

        self.viewLayout.addWidget(self.scroll_area)

        self.widget.setMinimumWidth(560)

        self._form_hint = self.scroll_area.widget().sizeHint().height()
        self._update_scroll_minimum()

    def resizeEvent(self, event):
        # 窗口足够高时滚动区保持表单自然高度（与无滚动时的外观一致）；
        # 高度不足时放宽最小高度让滚动区跟随收缩，防止中心部件整体溢出窗口裁掉按钮
        self._update_scroll_minimum()

        super().resizeEvent(event)

    def _update_scroll_minimum(self):
        margins = self.viewLayout.contentsMargins()
        available = self.height() - self.buttonGroup.height() - margins.top() - margins.bottom() - 4
        minimum = max(120, min(self._form_hint, available))

        if self.scroll_area.minimumHeight() != minimum:
            self.scroll_area.setMinimumHeight(minimum)

    def on_restore_default(self):
        self.prompt_box.setPlainText(DefaultValue.summary_prompt)

    def accept(self):
        config.set(config.summary_base_url, self.base_url_box.text().strip().rstrip("/"))
        config.set(config.summary_api_key, self.api_key_box.text().strip())
        config.set(config.summary_model, self.model_box.currentText().strip())
        config.set(config.summary_prompt, self.prompt_box.toPlainText())

        return super().accept()
